Node root field
digiaonline/graphql-relay-php pull request #6
Opened 2018-09-09 21:33 UTC by symm

Adds tooling to assist implementation of Relay [Node root field](https://facebook.github.io/relay/graphql/objectidentification.htm#sec-Node-root-field)

Changes proposed in this pull request:
 * Add `Node` class for converting to/from NodeIds
 * Document how to implement the node root field

Fixes #5

2018-09-09 21:42 UTC, cniska requested changes
Added some comments, other than that, LGTM. Thanks for the PR. 🙂

2018-09-09 21:42 UTC, crisu83 commented on src/Node.php
> +        $decoded = base64_decode($id, true);
Add a `\` before the fn call.

2018-09-09 21:42 UTC, crisu83 commented on src/Node.php
> +    private $type;
Add docblocks for the fields and methods.

2018-09-09 21:42 UTC, crisu83 commented on tests/Functional/StarWarsConnectionTest.php
> +          node(id: "' .$id .'") {
I would use double quotes for the query string as well as inline vars.

2018-09-09 21:55 UTC, symm commented
Cheers for the feedback @crisu83 I've applied a fix

2018-09-10 06:19 UTC, Jalle19 approved these changes

2018-09-10 08:16 UTC, Jalle19 commented on tests/Functional/starWarsSchema.php
> +function nodeResolver($root, $args)
Since `$root` is not used in this method we could skip taking it as a parameter IMO

2018-09-10 09:29 UTC, cniska approved these changes
Added some more comments, but other than it looks good to me.

2018-09-10 09:29 UTC, crisu83 commented on README.md
> +$node->getId(); //1
Maybe a bit nit-picky but you could add a space after the `//`.

2018-09-10 09:29 UTC, crisu83 commented on tests/Functional/StarWarsConnectionTest.php
> +          node(id: "' .$id .'") {
I would use double quotes and string interpolation here.

2018-09-10 18:41 UTC, merged

2018-09-11 07:34 UTC, crisu83 commented
@symm Thanks again for this PR. Feel free to join us on our open source Slack if you want. You can get an invite here: https://digiaopensource-slack.now.sh. All discussion related to our PHP GraphQL projects happen under the #graphql-php channel.